# Generated by Django 5.2.9 on 2025-12-24 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_review_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport_rf', 'Паспорт РФ'), ('passport_foreign', 'Загранпаспорт'), ('birth_cert', 'Свидетельство о рождении')], max_length=20, verbose_name='Тип документа')),
                ('series', models.CharField(blank=True, max_length=10, verbose_name='Серия')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(verbose_name='Дата окончания срока действия')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tours.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Документ клиента',
                'verbose_name_plural': 'Документы клиентов',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Страховая компания')),
                ('policy_number', models.CharField(max_length=50, verbose_name='Номер полиса')),
                ('start_date', models.DateField(verbose_name='Дата начала страховки')),
                ('end_date', models.DateField(verbose_name='Дата окончания страховки')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='tours.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Страховка',
                'verbose_name_plural': 'Страховки',
            },
        ),
    ]
